=== nikorenos/XML-files-editor/src/main/resources/people_schema.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="people">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="employee" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="pesel" type="xs:positiveInteger"/>
                            <xs:element name="firstname" type="xs:string"/>
                            <xs:element name="lastname" type="xs:string"/>
                            <xs:element name="phone" type="xs:positiveInteger"/>
                        </xs:sequence>
                        <xs:attribute name="id" type="xs:positiveInteger" use="required"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== nikorenos/XML-files-editor/src/main/resources/people.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<people xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:schemaLocation="people_schema.xsd">
    <employee id="1">
        <pesel>81032401612</pesel>
        <firstname>John</firstname>
        <lastname>Smith</lastname>
        <phone>500300200</phone>
    </employee>
    <employee id="3">
        <pesel>41032401612</pesel>
        <firstname>John</firstname>
        <lastname>Smith</lastname>
        <phone>200300200</phone>
    </employee>
</people>

=== nikorenos/XML-files-editor/src/main/resources/test.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<people xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:schemaLocation="people_schema.xsd">
    <employee id="1">
        <pesel>55555555555</pesel>
        <firstname>Micheal</firstname>
        <lastname>Milko</lastname>
        <phone>11111111</phone>
    </employee>
    <employee id="3">
        <pesel>11115555555</pesel>
        <firstname>Micheal</firstname>
        <lastname>Milko</lastname>
        <phone>11111111</phone>
    </employee>
</people>
